import { useEffect, useState } from 'react'
import { ArrowLeft, Check, Eye, LogIn, Pause, Play, RotateCcw } from 'lucide-react'
import { Nav } from '../components/Nav'
import { QuickSchedule } from '../components/QuickSchedule'
import { Score } from '../components/Score'
import { useMatches } from '../hooks/useMatches'
import { isSupabaseConfigured, supabase } from '../lib/supabase'
import type { Match, Team } from '../types'
import { sportName } from '../utils'

type Action={type:string;team?:'a'|'b';value?:number}
export function Scorer(){
 const{matches,setMatches,demo,refresh}=useMatches(),[selected,setSelected]=useState<Match>(),[registeredTeams,setRegisteredTeams]=useState<Team[]>([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[session,setSession]=useState<any>(null),[role,setRole]=useState<'admin'|'scorer'>('scorer'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{if(selected){const fresh=matches.find(m=>m.id===selected.id);if(fresh)setSelected(fresh)}},[matches])
  useEffect(()=>{if(session)supabase.from('profiles').select('role').eq('id',session.user.id).single().then(({data})=>data&&setRole(data.role))},[session])
 useEffect(()=>{if(session)supabase.from('teams').select('*').order('name').then(({data})=>data&&setRegisteredTeams(data))},[session])
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);const{error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?.message||'');setBusy(false)}
 const act=async(action:Action)=>{if(!selected)return;setBusy(true);setMessage('');if(demo){const updated=localApply(selected,action);setSelected(updated);setMatches(xs=>xs.map(x=>x.id===updated.id?updated:x));setBusy(false);return}const{error}=await supabase.rpc('apply_score_event',{p_match_id:selected.id,p_action:action});if(error)setMessage(error.message);else await refresh();setBusy(false)}
 if(isSupabaseConfigured&&!session)return <><Nav/><main className="portal centered"><form className="login-card" onSubmit={login}><span className="icon-badge"><LogIn/></span><h1>Scorer sign in</h1><p>Use the account assigned to your ground.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<p className="error">{message}</p>}<button className="primary" disabled={busy}>Sign in</button></form></main></>
 if(!selected){const assigned=demo||role==='admin'?matches:matches.filter(m=>m.scorer_id===session?.user.id),active=assigned.filter(m=>!['completed','cancelled'].includes(m.status)),completed=assigned.filter(m=>m.status==='completed').sort((a,b)=>+new Date(b.updated_at)-+new Date(a.updated_at)),teamOptions=registeredTeams.length?registeredTeams:Array.from(new Map(matches.flatMap(m=>[m.team_a,m.team_b]).map(t=>[t.id,t])).values());return <><Nav/><main className="portal"><div className="portal-head"><div><span className="kicker">SCORER CONSOLE</span><h1>Match desk</h1><p>Register, start and score your ground matches.</p></div>{demo&&<span className="demo-badge">DEMO MODE</span>}</div><div className="scorer-dashboard"><section><QuickSchedule teams={teamOptions} onCreated={refresh} compact/><h2 className="desk-heading">Ready to score <span>{active.length}</span></h2><div className="match-picker">{active.map(m=><button key={m.id} onClick={()=>setSelected(m)}><div><small>{m.status}</small><b>{sportName(m.sport)} · {m.gender}</b><span>{m.team_a.short_name} vs {m.team_b.short_name} · {m.venue}</span></div><strong>{new Date(m.scheduled_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</strong></button>)}{!active.length&&<p className="empty-copy">No assigned matches. Register the next match above.</p>}</div></section><aside className="completed-list"><h2>Finished matches</h2><p>Results are locked and view-only.</p>{completed.map(m=><button key={m.id} onClick={()=>setSelected(m)}><Eye/><span><b>{sportName(m.sport)}</b><small>{m.team_a.short_name} vs {m.team_b.short_name}</small></span></button>)}</aside></div></main></>}
 const setSport=['badminton','volleyball','table_tennis'].includes(selected.sport),completed=selected.status==='completed'
 return <><Nav/><main className="portal scorer-wrap"><button className="back" onClick={()=>setSelected(undefined)}><ArrowLeft/>All matches</button><section className={`scorer-card ${completed?'read-only':''}`}><div className="scorer-top"><div><span>{sportName(selected.sport)} · {selected.gender}</span><h1>{selected.team_a.short_name} <i>vs</i> {selected.team_b.short_name}</h1><small>{selected.venue}</small></div><b className={`match-status ${selected.status}`}>{completed?<Eye/>:'●'} {selected.status}</b></div><div className="scorer-score"><Score match={selected}/></div>{completed?<div className="locked-result"><Check/><div><b>Final result — view only</b><span>This match is complete and cannot be scored or reopened.</span></div></div>:selected.status==='scheduled'?<div className="start-match"><p>Confirm both teams are present on the ground.</p><button className="primary" onClick={()=>act({type:'start_match'})} disabled={busy}><Play/>Start match</button></div>:<><div className="score-controls">{controls(selected,act,busy)}</div><div className="utility-controls"><button onClick={()=>act({type:'undo'})} disabled={busy}><RotateCcw/>Undo last</button>{setSport&&<button onClick={()=>act({type:'next_set'})} disabled={busy}>Next set</button>}{['football','basketball'].includes(selected.sport)&&<><button onClick={()=>act({type:selected.score_state.timer_status==='running'?'pause_timer':'start_timer'})}>{selected.score_state.timer_status==='running'?<Pause/>:<Play/>}{selected.score_state.timer_status==='running'?'Pause':'Start'} timer</button><button onClick={()=>act({type:'next_period'})}>Next period</button></>}<button className="finish" onClick={()=>{if(window.confirm('Finish this match? The score will become permanently read-only.'))act({type:'finish'})}}><Check/>Finish match</button></div></>}{message&&<p className="error">{message}</p>}</section></main></>
}
function controls(m:Match,act:(a:Action)=>void,busy:boolean){const team=(side:'a'|'b',label:string,value=1)=><button disabled={busy} onClick={()=>act({type:'score',team:side,value})}><span>{side==='a'?m.team_a.short_name:m.team_b.short_name}</span><strong>{label}</strong></button>;if(m.sport==='cricket')return <div className="cricket-buttons">{[0,1,2,3,4,6].map(v=><button key={v} onClick={()=>act({type:'runs',value:v})}>{v}</button>)}<button className="danger" onClick={()=>act({type:'wicket'})}>WICKET</button><button onClick={()=>act({type:'extra',value:1})}>WIDE +1</button><button onClick={()=>act({type:'extra',value:1})}>NO BALL +1</button></div>;if(m.sport==='basketball')return <div className="team-controls"><div>{[1,2,3].map(v=>team('a',`+${v}`,v))}</div><div>{[1,2,3].map(v=>team('b',`+${v}`,v))}</div></div>;if(m.sport==='chess')return <div className="chess-buttons"><button onClick={()=>act({type:'chess_result',team:'a'})}>{m.team_a.short_name} wins</button><button onClick={()=>act({type:'chess_draw'})}>Draw</button><button onClick={()=>act({type:'chess_result',team:'b'})}>{m.team_b.short_name} wins</button></div>;return <div className="team-controls"><div>{team('a',m.sport==='football'?'GOAL +':'+1')}</div><div>{team('b',m.sport==='football'?'GOAL +':'+1')}</div></div>}
function localApply(m:Match,a:Action):Match{const n=structuredClone(m),s=n.score_state as any;if(a.type==='start_match')n.status='live';if(a.type==='score'){const k=['badminton','volleyball','table_tennis'].includes(m.sport)?(a.team==='a'?'pointsA':'pointsB'):(a.team==='a'?'teamA':'teamB');s[k]=(s[k]||0)+(a.value||1)}if(a.type==='runs'){s.runs=(s.runs||0)+(a.value||0);s.balls=(s.balls||0)+1}if(a.type==='wicket'){s.wickets=(s.wickets||0)+1;s.balls=(s.balls||0)+1}if(a.type==='extra')s.runs=(s.runs||0)+(a.value||1);if(a.type==='next_set'){s.setsA=(s.setsA||0)+(s.pointsA>s.pointsB?1:0);s.setsB=(s.setsB||0)+(s.pointsB>s.pointsA?1:0);s.pointsA=0;s.pointsB=0;s.currentSet=(s.currentSet||1)+1}if(a.type==='start_timer'){s.timer_started_at=new Date().toISOString();s.timer_status='running'}if(a.type==='pause_timer')s.timer_status='paused';if(a.type==='finish')n.status='completed';n.updated_at=new Date().toISOString();return n}
