import { useState } from 'react'
import { ArrowDown, ArrowUp, Megaphone, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useAnnouncements } from '../hooks/useAnnouncements'
import { supabase } from '../lib/supabase'

export function AnnouncementManager(){
 const{announcements,refresh}=useAnnouncements(),[message,setMessage]=useState(''),[editing,setEditing]=useState<string>(),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');const result=editing?await supabase.from('announcements').update({message:message.trim(),updated_at:new Date().toISOString()}).eq('id',editing):await supabase.from('announcements').insert({message:message.trim(),priority:announcements.length});if(result.error)setError(result.error.message);else{setMessage('');setEditing(undefined);await refresh()}setBusy(false)}
 const mutate=async(id:string,values:Record<string,unknown>)=>{setError('');const{error}=await supabase.from('announcements').update({...values,updated_at:new Date().toISOString()}).eq('id',id);if(error)setError(error.message);else refresh()}
 const remove=async(id:string)=>{if(!window.confirm('Delete this display update?'))return;const{error}=await supabase.from('announcements').delete().eq('id',id);if(error)setError(error.message);else refresh()}
 const edit=(id:string,text:string)=>{setEditing(id);setMessage(text)}
 return <section className="announcement-admin"><div className="announcement-title"><span><Megaphone/></span><div><h2>EGS display updates</h2><p>Changes appear instantly in the LED ticker.</p></div></div><form onSubmit={save}><textarea maxLength={300} placeholder="Type an announcement, result update or instruction…" value={message} onChange={e=>setMessage(e.target.value)} required/><div><small>{message.length}/300</small>{editing&&<button type="button" className="cancel-edit" onClick={()=>{setEditing(undefined);setMessage('')}}><X/>Cancel</button>}<button className="primary" disabled={busy}><Plus/>{editing?'Update':'Publish'}</button></div></form>{error&&<p className="error">{error}</p>}<div className="announcement-list">{announcements.map((item,index)=><article key={item.id} className={item.active?'':'inactive'}><button className="visibility-toggle" onClick={()=>mutate(item.id,{active:!item.active})}><i/>{item.active?'ON DISPLAY':'HIDDEN'}</button><p>{item.message}</p><div><button title="Move up" disabled={index===0} onClick={()=>mutate(item.id,{priority:item.priority+1})}><ArrowUp/></button><button title="Move down" disabled={index===announcements.length-1} onClick={()=>mutate(item.id,{priority:item.priority-1})}><ArrowDown/></button><button title="Edit" onClick={()=>edit(item.id,item.message)}><Pencil/></button><button title="Delete" className="delete" onClick={()=>remove(item.id)}><Trash2/></button></div></article>)}{!announcements.length&&<p className="empty-copy">No updates yet. Publish the first ticker message above.</p>}</div></section>
}
