import { useState } from 'react'
import { CalendarPlus, X } from 'lucide-react'
import { isSupabaseConfigured, supabase } from '../lib/supabase'
import type { Sport, Team } from '../types'
import { sportName } from '../utils'

const sports:Sport[]=['football','badminton','volleyball','basketball','cricket','table_tennis','chess']
const initial={sport:'football' as Sport,gender:'men',teamA:'',teamB:'',scheduledAt:new Date(Date.now()+15*60000).toISOString().slice(0,16),venue:'Main Ground'}
export function QuickSchedule({teams,onCreated,compact=false}:{teams:Team[];onCreated?:()=>void;compact?:boolean}){
 const[open,setOpen]=useState(!compact),[form,setForm]=useState(initial),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setNotice('');if(!isSupabaseConfigured){setNotice('Preview only — connect Supabase to save.');setBusy(false);return}const{error}=await supabase.rpc('create_scheduled_match',{p_sport:form.sport,p_gender:form.gender,p_team_a:form.teamA.trim(),p_team_b:form.teamB.trim(),p_scheduled_at:new Date(form.scheduledAt).toISOString(),p_venue:form.venue.trim()});if(error)setNotice(error.message);else{setNotice('Match scheduled and assigned to you.');setForm({...initial,scheduledAt:new Date(Date.now()+15*60000).toISOString().slice(0,16)});onCreated?.()}setBusy(false)}
 if(!open)return <button className="quick-create" onClick={()=>setOpen(true)}><CalendarPlus/>Register & schedule match</button>
 return <form className={`quick-schedule ${compact?'compact-form':''}`} onSubmit={save}><div className="quick-title"><div><CalendarPlus/><span><b>On-ground registration</b><small>Type a new team or select an existing one</small></span></div>{compact&&<button type="button" onClick={()=>setOpen(false)}><X/></button>}</div><div className="quick-fields"><label>Sport<select value={form.sport} onChange={e=>setForm({...form,sport:e.target.value as Sport})}>{sports.map(s=><option value={s} key={s}>{sportName(s)}</option>)}</select></label><label>Category<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="men">Boys / Men</option><option value="women">Girls / Women</option><option value="mixed">Mixed</option></select></label><label>Team / Player A<input list="team-options" placeholder="Type school or team" value={form.teamA} onChange={e=>setForm({...form,teamA:e.target.value})} required/></label><label>Team / Player B<input list="team-options" placeholder="Type school or team" value={form.teamB} onChange={e=>setForm({...form,teamB:e.target.value})} required/></label><datalist id="team-options">{teams.map(t=><option value={t.name} key={t.id}/>)}</datalist><label>Start time<input type="datetime-local" value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})} required/></label><label>Ground / Court<input placeholder="e.g. Court 2" value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})} required/></label></div><button className="primary" disabled={busy}>{busy?'Saving…':'Create schedule'}</button>{notice&&<p className={notice.includes('scheduled')?'notice':'error'}>{notice}</p>}</form>
}
